
data_load:
  local_dir: 'E:/University-Georgia Tech/CS7643_deeplearning/groupproject/competition_VfIpjyh/'

data_split:
  frac: 0.1
  test_size: 0.25

data_preprocess:
  batch_size: 4



model_name: 'RestNet' # 'RestNet', 'EfficientNet'

optimizer_name: 'SGD' # 'SGD', 'Adam'

loss_name: 'CrossEntropyLoss' # 'BCEWithLogitsLoss'


vit_hyper_p:
  image_size: 224  # Input image size (224x224)
  patch_size: 16   # Patch size
  num_layers: 4
  num_heads: 4     # Number of attention heads
  hidden_dim: 128
  mlp_dim: 512     # Dimension of MLP layers
  dropout: 0.1      # Dropout rate
  num_classes: 8

optimizer_hyper_p:
  lr: 0.0001
  momentum: 0.9


### training parameters ###
train:
  num_epochs: 1
  device: 'cpu'
  model_save_path: 'model/'
  plt_pic_save_path: 'plt_pic/'